version: '3.7'

services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sgmea-db
#    ports:
#      - "3306:3306"
    networks:
      - sgmea-network

  sgmea-backend:
    container_name: sgmea-backend
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/sgmea-db?allowPublicKeyRetrieval=true

    networks:
      - sgmea-network

networks:
  sgmea-network:
    driver: bridge  # O driver bridge é o padrão e é utilizado para comunicação entre contêineres na mesma máquina
